fix QA reviews
divinecharlotte/north-star-team7 pull request #16
Opened 2023-08-24 15:54 UTC by divinecharlotte

fixed reviews from QAin this section

2023-08-28 13:08 UTC, ishimwe07 approved these changes
LGTM.

2023-08-28 13:08 UTC, NelHim requested changes
1. Make the content centered on very large screens. above 2xl

2023-08-29 13:51 UTC, NelHim approved these changes

2023-08-29 13:55 UTC, NelHim commented
Good Job

2023-08-29 13:55 UTC, merged