fix subSahara QA
divinecharlotte/north-star-team7 pull request #19
Opened 2023-08-25 16:47 UTC by divinecharlotte

fixed the given QA reviews on this section

2023-08-28 12:49 UTC, ishimwe07 requested changes
On my larger screen you can add the background colors to the whole page.


![image](https://github.com/divinecharlotte/north-star-team7/assets/81089765/030fd9b9-03f2-490f-b7d3-8c00e68f5be5)

2023-08-28 12:49 UTC, ishimwe07 commented on src/sections/subSahara.html
> +    <footer class="flex lg:flex-row flex-col  justify-between items-center lg:pr-48 h-80 p-2 xl:bg-no-repeat lg:pl-36 " style="background-image: url(../../images/bg_hero-1.webp)">
below the footer there is no background color of blue, it's just oblique line below the linear gradient.


![image](https://github.com/divinecharlotte/north-star-team7/assets/81089765/92c86b1b-f873-4f10-bc32-c0d63aba1260)

2023-08-28 12:54 UTC, NelHim approved these changes
1. Try to center only the content, not the background on very large screens
2. Make the bottom oblique

2023-08-28 12:58 UTC, NelHim requested changes
1. Try to center only the content, not the background on very large screens
2. make sure your top and bottom are oblique

2023-08-29 13:58 UTC, NoellaPromise approved these changes
Good Job!

2023-08-29 14:02 UTC, NelHim approved these changes

2023-08-29 14:02 UTC, NelHim commented
Good Job!

2023-08-29 14:07 UTC, ishimwe07 approved these changes
Looks Good now.

2023-08-29 14:07 UTC, merged