Ft/qualitat
divinecharlotte/north-star-team7 pull request #3
Opened 2023-08-17 15:26 UTC by NelHim

2023-08-21 13:20 UTC, ishimwe07 requested changes
You did  a good job, congratulations on that.
But I suggested some changes to make it even better.

2023-08-21 13:20 UTC, ishimwe07 commented on src/sections/qualitat.html
> +            <span class="h-1 w-full bg-green"></span>
May be you can try to make those green lines equal as it is in the figma design.

2023-08-21 13:20 UTC, ishimwe07 commented on src/sections/qualitat.html
> +
Behind the name "Matthias Moosburger" in that paragraph there is supposed to be a bit rotated green line. So you can consider adding it.

2023-08-22 10:36 UTC, ishimwe07 approved these changes
Good.

2023-08-22 10:36 UTC, divinecharlotte approved these changes
# Hello @NelHim      😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 

 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

2023-08-22 10:45 UTC, merged