feature: Added the Fragen und Antworten section and the footer section.
divinecharlotte/north-star-team7 pull request #9
Opened 2023-08-18 15:52 UTC by ishimwe07

feature: Added the Fragen section and the footer.

2023-08-21 13:37 UTC, NelHim requested changes

2023-08-21 13:37 UTC, NelHim commented on src/sections/fragenAntworten.html
> +    </div>
Try to keep section in the center on  different screen sizes

2023-08-21 14:16 UTC, ishimwe07 commented on src/sections/fragenAntworten.html
> +    </div>
Done.
You can check it out.

2023-08-21 14:34 UTC, NelHim approved these changes
I like your fixes.

2023-08-22 14:20 UTC, divinecharlotte approved these changes

2023-08-22 14:20 UTC, merged